examLetter/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm


#app_name ='examletter'


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path('signup/', views.signup, name='signup'),
    #path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm,template_name='examLetter/login.html')),
    path('accounts/login/', auth_views.LoginView.as_view(authentication_form=LoginForm,template_name='examLetter/login.html')),
    path('logout/', views.logout_view, name='logout'),  
    path("examination/", include("examination.urls")),
    path("letter/", include("letter.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

letter/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from . views import upload_excel

app_name = "letter"


urlpatterns = [
    path("",views.index, name="index"),
    path("create/", views.upload_excel ,name='createLetter'),
    path("mailsample/<int:letter_id>", views.mailSample, name='mailsample'),
    path("details/<int:letter_id>", views.letterDetails ,name='details'),
    path('deleteAll/', views.deleteAll, name='deleteAll'),
    path('send-email/', views.send_personalized_email, name='send-email'),
    path('send-letter/', views.sendLetter, name='send-letter'),

]

letter/models.py
from django.db import models
from examination.models import Examination

class TimeStampedModel(models.Model):
    """Abstract base class that adds created_at and updated_at fields to models."""
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Create your models here.
class Letter(TimeStampedModel):
    examination = models.ForeignKey(Examination, on_delete=models.CASCADE,related_name='letters')
    surname = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    institutionAddress = models.CharField(max_length=300)
    role = models.CharField(max_length=300)
    membershipOrFellowship = models.CharField(max_length=300)
    hotel = models.CharField(max_length=400, default='')
    meal = models.CharField(max_length=400, default='')
    cc = models.CharField(max_length=400, default='')
    centerOfTheExamination = models.CharField(max_length=200)
    countryOfTheExamination = models.CharField(max_length=200, default='')
    onOrBefore = models.CharField(max_length=200, default='')
    holdAt  = models.CharField(max_length=200, default='')
    InstitutionAddressCountry  = models.CharField(max_length=300, default='')
    faculty  = models.CharField(max_length=200, default='')
    arrivalDate = models.CharField(max_length=20, default='')
    depatureDate = models.CharField(max_length=20, default='')
    email = models.CharField(max_length=200)
    userType = models.CharField(max_length=200, default='')
    status = models.CharField(max_length=200, default='Not Sent')
    

    def __str__(self):
        return self.examination.examName
 

letter/forms.py
from django import forms
from . models import Examination
from faculty.models import Faculty

class ExcelUploadForm(forms.Form):
    #examination = forms.ModelChoiceField(queryset=Examination.objects.all(),empty_label='Select an Examination'
    #                                     ,widget=forms.Select(attrs={'class': 'form-control'}))
    file = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    
class SearchForm(forms.Form):
    STATUS_CHOICES = [
         ("", "Select Status"),
         ("Not Sent", "Not Sent"),
         ("Sent", "Sent"),
    ]
    examination = forms.ModelChoiceField(queryset=Examination.objects.all(), 
                                         required=True, empty_label="Select Examination")
    faculty = forms.ModelChoiceField(queryset=Faculty.objects.all(), required=True,
                                     to_field_name="facultyName",
                                     empty_label="Select Faculty")
    
    status = forms.ChoiceField(
        choices=STATUS_CHOICES,
        label="Status",
        required=True
    )

letter/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.mail import EmailMultiAlternatives #for email sending
from django.template.loader import render_to_string #for sending email
from django.utils.html import strip_tags  #for sending email
from django.db.models import Q 
from django.conf import settings
import pandas as pd
from django.contrib import messages
from . forms import ExcelUploadForm
from .models import Letter
from . models import Examination
from xhtml2pdf import pisa
from django.template.loader import get_template
from io import BytesIO
import tempfile
import mimetypes
from django.core.mail import EmailMessage
from faculty.models import Faculty
from .forms import SearchForm
import os

# Create your views here.
@login_required
def index(request):
    examinations = Examination.objects.all()
    faculties = Faculty.objects.all()
    form = SearchForm(request.POST)
    letters = Letter.objects.none()
    page_obj = None 


    if request.method == 'POST':
            if form.is_valid():
                #return HttpResponse('am ai getting the right thing')
                examination = request.POST.get('examination')
                faculty =request.POST.get('faculty')
                status = request.POST.get('status')
                #return HttpResponse(status)

                letters = Letter.objects.filter(examination_id = examination,
                                         faculty__icontains=faculty,
                                         status__iexact=status)
                paginator = Paginator(letters, 50)
                page_number = request.GET.get("page")
                page_obj = paginator.get_page(page_number) 
                
    return render(request, 'letter/index.html',
                  {'letters':letters ,
                   'form': form,
                    'page_obj': page_obj,
                   'faculties': faculties,
                   'examinations':examinations
                   })



@login_required
def mailSample(request, letter_id):
    letter = get_object_or_404(Letter, id=letter_id)
    #return HttpResponse(letter)
    return render(request, 'letter/mailsample.html',{'letter': letter})

@login_required
def deleteAll(request):
    records = Letter.objects.all()
    if records.delete():
        return HttpResponse("All records deleted")
    
@login_required
def letterDetails(request, letter_id):
    letter  = get_object_or_404(Letter, id=letter_id)
    return render(request, 'letter/details.html', {'letter': letter})


#This will uplload excel file for me
@login_required
def upload_excel(request):
    if request.method == 'POST':
        form = ExcelUploadForm(request.POST,request.FILES)
        if form.is_valid():
            excel_file = request.FILES['file']
            requestedExaminationId = request.POST.get('examination')
            #i willl read excel file now
            df = pd.read_excel(excel_file, dtype=str, keep_default_na=False)
            df.columns = df.columns.str.strip()  # Remove unwanted spaces
            df["ArrivalDate"] = df["ArrivalDate"].astype(str)
            df["DepatureDate"] = df["DepatureDate"].astype(str)
          
            #iterate thrrough rows
            for _, row in df.iterrows():
                arrival_date = str(row['ArrivalDate']).strip()
                depature_date = str(row['DepatureDate']).strip()
                Letter.objects.create(
                    examination_id = requestedExaminationId,
                    surname=row['Surname'],
                    name = row['Name'],
                    institutionAddress = row['InstitutionAddress'],
                    role = row['Role'],
                    membershipOrFellowship = row['MembershipOrFellowship'],
                    hotel = row['Hotel'],
                    centerOfTheExamination = row['CenterOfTheExamination'],
                    meal = row['Meal'],
                    cc = row['CC'],
                    arrivalDate=arrival_date,  # Explicitly save as a string
                    depatureDate=depature_date, 
                    email = row['Email'],
                    faculty = row['Faculty'],
                    onOrBefore = row['OnOrBefore'],
                    holdAt = row['HoldAt'],
                    countryOfTheExamination = row['CountryOfTheExamination'],
                    InstitutionAddressCountry = row['InstitutionAddressCountry'],
                    userType = row['UserType'],
                )
            #return HttpResponse('Data Imported Successfully!')
            messages.success(request, "Records successfully imported")  
            return redirect('examination:index')
    else:
        form =ExcelUploadForm()
    examinations = Examination.objects.all()
    
    return render(request, 'letter/create.html',{'form':form,'examinations':examinations})


def send_personalized_email(request):
   
    #letters = Letter.objects.all()  # Fetch all users
    #letters = Letter.objects.all() #.values('email')  # Fetch first Letter instance
    letters = Letter.objects.filter(examination_id = 5)
    #return HttpResponse(letters)
    #letters = ['clementcrownrise@gmail.com','clementcrownrise@yahoo.com']
    for letter in letters:
        #return HttpResponse(letter.email)
        pdf_buffer = generate_pdf(letter.email)  # Generate a PDF for the user
        
        if not pdf_buffer:
            print(f"Failed to generate PDF for {letter}")
            continue  # Skip this user if PDF generation fails
        
        # Email details
        subject = "Your Personalized Document"
        html_message = render_to_string('emails/email_template.html', {'letter': letter})
        plain_message = strip_tags(html_message)  # Convert HTML to plain text
        email = EmailMessage(
            subject,
            plain_message,
            'info@wacp-coam',  # Replace with your sender email
            [email],  # Assuming Letter model has an 'email' field
        )
        
        # Attach the PDF
        email.attach(f"document_{letter.id}.pdf", pdf_buffer.getvalue(), "application/pdf")
        
        # Send email
        email.send()
        print(f"Email sent to {letter.email}")

    print("All emails have been processed.")






@login_required
def createLetter(request):
    pass
    #return HttpResponse("this is for letter creation")
   # return render(request, 'letter/create.html')

#this triggers the mail
@login_required
def send_letter_view(request):
    #sendLetter() the main one that sends letter
    return HttpResponse("Emails have been sent!")

def generate_pdf(letter):

    """Generates a PDF from the letter template"""
    html_content = render_to_string("emails/attachment.html", {"letter": letter})
    pdf_file = BytesIO()
    
    # Convert HTML to PDF
    pisa_status = pisa.CreatePDF(html_content, dest=pdf_file)
    
    if pisa_status.err:
        return None
    
    pdf_file.seek(0)  # Reset file pointer to start
    return pdf_file



@login_required
def sendLetter(request):
    examination = request.POST.get('examination')
    facultyName = request.POST.get('faculty')
    status = request.POST.get('status')
    letters = Letter.objects.filter(examination_id = examination,
                                        faculty__icontains=facultyName,status__iexact=status)
    
    #return HttpResponse(letters)
    examination = Examination.objects.get(id = examination)
    subject = examination.examName
    #return HttpResponse(examination.examName)
    totFlyer = examination.totFlyers
    

    abujaTimeTable = examination.timetableAbuja
    accraTimeTable = examination.timetableAccra
    ibadanTimeTable = examination.timetableIbadan
    
    foreign_pdf_file = examination.travelProtocol
    
        
    for letter in letters:
       
        html_message = render_to_string("emails/letter_template.html", {"letter": letter})
        plain_message = strip_tags(html_message)  # Remove HTML for plain text version

        if letter.email:
        # Split emails by semicolon and remove extra spaces
            recipient_list = [email.strip() for email in letter.email.split(";") if email.strip()]
            bcc =['ha@wacpcoam.org', 'goodluckadmin@wacpcoam.org',
        'hodexams@wacpcoam.org', 
          'sanni.jimah@wacpcoam.org',
             'flightticket@wacpcoam.org',
             'clementcrownrise@gmail.com',
               'secgen@wacpcoam.org']
       
        email = EmailMultiAlternatives(
            subject,
            plain_message,  # Plain text content
            request.user.username or "adeyemi.tosin@wacpcoam.org" , # Or any other valid email
            recipient_list,  # Recipient list
            bcc = bcc
        )
        email.attach_alternative(html_message, "text/html")  # Attach HTML content

        #i attached the generated guys here
       

        pdf_file = generate_pdf(letter)
        if pdf_file:
            email.attach(f"Invitation_Letter_{letter.surname}.pdf", pdf_file.getvalue(), "application/pdf")

        if  letter.InstitutionAddressCountry.strip().lower() != letter.countryOfTheExamination.strip().lower():                
                with open(foreign_pdf_file.path, "rb") as f:
                    email.attach(os.path.basename(foreign_pdf_file.path),
                                  f.read(),
                                  "application/pdf")                
          
        
        if letter.centerOfTheExamination.strip().upper() == "ABUJA":
                with open(abujaTimeTable.path, "rb") as f:
                    email.attach(os.path.basename(abujaTimeTable.path),
                                  f.read(), "application/pdf")
            
        elif letter.centerOfTheExamination.strip().upper() == "IBADAN":
                 with open(ibadanTimeTable.path, "rb") as f:

templates/letter/create.html
{% extends 'examination/base.html' %} 

{% block title %} Create Examination {% endblock %}

{% block pagetitle %}
<div class="d-flex justify-content-between align-items-center">
   <h4>Create Letters</h4> 
<a class="btn btn-primary" href="{% url 'letter:index' %}">
    Back to Letter List</a>
    {% load static %}
    <a class="btn btn-dark" href="{% static 'WACPLetterTemplate.xlsx' %}">
        Download Template</a>
</div>
 
{%  endblock %}

{% block body %}
       

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group mb-5">
    <label for="" class="mb-3">Select Examination</label>
    <select name="examination" id="" class="form-control">
        <option value="selected">Please Select an Examination</option>
    {% for examination in examinations %}
    <option value="{{ examination.id}}">{{ examination}}</option>
{% endfor %}
</select>
</div>
    {{ form.as_p  }}
    <button type="submit" class="btn btn-primary form-control mt-2">Upload</button>
</form>

{% endblock %}

templates/letter/details.html
{% extends 'examination/base.html' %} 

{% block title %} Letter {% endblock %}

{% block pagetitle %} 
<div class="d-flex justify-content-between align-items-center">
    <h4>Details for: <b>{{letter.surname}}, {{ letter.name }}</b></h4> 
 <a class="btn btn-primary"
  href="{% url 'letter:createLetter' %}">Create Letters</a>
  
 </div>
{%  endblock %}

{% block body %}

<table class="table table-bordered">
    <tr>
      <td>Surname Name</td>
      <td>{{ letter.surname }}</td>
    </tr>
    <tr>
      <td>Other Names</td>
      <td>{{ letter.name }}</td>
    </tr>
    <tr>
      <td>Faculty</td>
      <td>{{ letter.faculty }}</td>
    </tr>
      <tr>
       <td>Institution Address</td>
      <td>{{ letter.institutionAddress }}</td> 
      </tr>
      <tr>
        <td>Institution Country</td>
       <td>{{ letter.InstitutionAddressCountry }}</td> 
       </tr>
       <tr>
        <td>Examination Center Country</td>
       <td>{{ letter.countryOfTheExamination }}</td> 
       </tr>
      <tr>
         <td>Role</td>
      <td>{{ letter.role }}</td>
      </tr>
     <tr>
       <td>Membership OR Fellowship</td>
      <td>{{ letter.membershipOrFellowship }}</td>
     </tr>
     <tr>
      <td>Hotel</td>
      <td>{{ letter.hotel }}</td>
     </tr>
      <tr>
         <td>CC</td>
      <td>{{ letter.cc }}</td>
      </tr>
     <tr>
       <td>Center of Examination</td>
      <td>{{ letter.centerOfTheExamination }}</td>
     </tr>
     <tr>
      <td>Hold At</td>
     <td>{{ letter.holdAt }}</td>
    </tr>
    <tr>
      <td>On or Before</td>
     <td>{{ letter.onOrBefore }}</td>
    </tr>
     <tr>
       <td>Arrival Date</td>
      <td>{{ letter.arrivalDate }}</td>
     </tr>
     <tr>
        <td>Departure Date</td>
       <td>{{ letter.depatureDate }}</td>
      </tr>
      <tr>
        <td>Email Address</td>
       <td>{{ letter.email }}</td>
      </tr>
      <tr>
        <td>User Type</td>
       <td>{{ letter.userType }}</td>
      </tr>
     
    
   </table>
   {% endblock %}

templates/letter/index.html
{% extends 'examination/base.html' %} 

{% block title %} Letter {% endblock %}

{% block pagetitle %} 
<div class="d-flex justify-content-between align-items-center">
    <h4>Letter</h4> 
 <a class="btn btn-primary"
  href="{% url 'letter:createLetter' %}">Create Letters</a>
  
 </div>
{%  endblock %}

{% block body %}

 
<div class="d-flex justify-content-between py-12">
<h2>Letters:</h2>
<form action="" method="POST" id="searchForm"
class="d-flex justify-content-between gap:10px">
   {% csrf_token %}
   
   {{ form.examination }}
   {{ form.faculty }}
   {{ form.status }}

   
    <button type="submit" class="btn btn-primary ml-2">Display</button>
    <button type="submit" onclick="document.getElementById('searchForm').action='/letter/send-letter/'" class="btn btn-primary ml-2">Send Letter</button>

    <button type="button" class="btn btn-danger"
     onclick="window.history.back()">Cancel</button>

</form>


</div><br><br>

<!-- Bordered Table -->
<table class="table table-bordered mt-[10px]">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Surname</th>
      <th scope="col">Name</th>
      <th scope="col">Examination Name</th>
      <th scope="col">Faculty</th>
      <th scope="col">Examination Center</th>
      <th scope="col">Status</th>
        <th>Action</th>
   </tr>
  </thead>
  <tbody>
      {% for letter in page_obj %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ letter.surname }}</td>
      <td>{{ letter.name }}</td>
      <td>{{ letter.examination.examName }}</td>
      <td>{{ letter.faculty }}</td>
      <td>{{ letter.centerOfTheExamination }}</td>
      <td>{{ letter.status }}</td>

      <td>
        <a href="{% url 'letter:details' letter.id  %}"> 
          <button class="btn btn-dark">View </button></a>
       <a href="{% url 'letter:mailsample' letter.id %}">
         <button class="btn btn-danger">View Letter</button></a> 

      </td>
    </tr>
    {%  empty %}
    <h4>Select an Examination and Faculty to display Letters</h4>
    {%  endfor %}
  </tbody>
</table>
<!-- End Bordered Table -->

<!--paginator here-->

<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>
{% endblock %}

templates/letter/upload.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Excel File</title>
</head>
<body>
    <h2>Upload Excel File</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>