examLetter/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm


#app_name ='examletter'


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path('signup/', views.signup, name='signup'),
    #path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm,template_name='examLetter/login.html')),
    path('accounts/login/', auth_views.LoginView.as_view(authentication_form=LoginForm,template_name='examLetter/login.html')),
    path('logout/', views.logout_view, name='logout'),  
    path("examination/", include("examination.urls")),
    path("letter/", include("letter.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examination/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.urls import path, include


app_name = 'examination'

urlpatterns = [
    path("",views.index, name="index"),
    path("create/", views.createExam ,name='createExam'),
    path("selected/", views.selected , name='selected'),
    path("details/<int:examination_id>", views.exam_details, name='details'),
    path("edit/<int:examination_id>", views.examEdit, name='edit'),
    path('delete/<int:examination_id>', views.deleteExam, name='deleteExam'),
]

letter/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from . views import upload_excel

app_name = "letter"


urlpatterns = [
    path("",views.index, name="index"),
    path("create/", views.upload_excel ,name='createLetter'),
    path("mailsample/<int:letter_id>", views.mailSample, name='mailsample'),
    path("details/<int:letter_id>", views.letterDetails ,name='details'),
    path('deleteAll/', views.deleteAll, name='deleteAll'),
    path('send-email/', views.send_personalized_email, name='send-email'),
    path('send-letter/', views.sendLetter, name='send-letter'),

]

examination/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field
from django.forms.widgets import DateInput
#from .forms import UploadFileForm


# Create your models here.
class Examination(models.Model):
    examName = models.CharField(max_length=200)
    totTopic = models.CharField(max_length=200)
    totFlyers =models.ImageField(upload_to='uploads/' , blank=True, null=True)
    totDate = models.CharField(max_length=200)
    totDetails = CKEditor5Field('TOT Details', config_name='comment')
    arrivalinfo = models.CharField(max_length=300)
    timetableIbadan = models.FileField(upload_to='uploads/')
    timetableAccra = models.FileField(upload_to='uploads/')
    timetableAbuja = models.FileField(upload_to='uploads/')
    travelProtocol = models.FileField(upload_to='uploads/')

    def __str__(self):
            return self.examName



    

examination/forms.py
from django import forms
import datetime
from .models import Examination
from django.forms.widgets import DateInput
from django_ckeditor_5.widgets import CKEditor5Widget
#class DateInput(forms.DateInput):
#    input_type = 'date'


class ExamForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.fields["totDetails"].required = False


    class Meta:
        model = Examination
        fields = "__all__"
        labels = {
            'examName': 'Exam Name',
            'totTopic': 'TOT Topic',
            'totFlyers': 'TOT Flyer(must be jpeg/jpg)',
            'totDate': 'TOT Date',
            'totDetails': 'TOT Details',
            'arrivalinfo': 'Arrival Information(for CEs)',
            'timetableIbadan': 'Timetable for Ibadan',
            'timetableAccra': 'Timetable for Accra',
            'timetableAbuja': 'Timetable for Abuja',
            'travelProtocol': 'Travel Protocol Document',
        }
        widgets = {  
             
            'examName': forms.TextInput(attrs={'class': 'form-control'}),
            'totTopic': forms.TextInput(attrs={'class': 'form-control'}),
            'totDate': forms.TextInput(attrs={'class': 'form-control'}),
            'arrivalinfo': forms.Textarea(attrs={'class': 'form-control'}),
            'totDetails': forms.Textarea(attrs={'class': 'form-control'}),
            'totFlyers': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'timetableIbadan': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'timetableAccra': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'timetableAbuja': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'travelProtocol': forms.ClearableFileInput(attrs={'class': 'form-control'}),

            #'examName' : forms.CharField(max_length=300,widget=forms.TextInput(attrs={'class': 'form-control'})),
            #'totTopic' : forms.CharField(max_length=400,widget=forms.TextInput(attrs={'class': 'form-control'})),
            #'totFlyers' : forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'})),
            #'totDate' : forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'})),
            #'arrivalinfo' : forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4})),
            #'totDetails' : forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 4})),
            #'timetableIbadan' : forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'})),
            #'timetableAccra' : forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'})),
            #'timetableAbuja' : forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'})),
            #'travelProtocol' : forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'})),
        }

       

examination/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from . models import Examination
from letter.models import Letter
from faculty.models import Faculty
from . forms import ExamForm


# Create your views here.

def selected(request):
    if request.method == 'POST':
        faculty = request.POST.get('faculty')
        results  = Letter.objects.filter(faculty__icontains=faculty)
        #return HttpResponse(results)
        return render(request, "examination/examDetails.html", {'results': results})


@login_required
def index(request):
    #return HttpResponse("All created exams would be listed here")
    examinations = Examination.objects.order_by('-id')
    paginator = Paginator(examinations, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(request, "examination/index.html",
                  {'examinations':examinations,'page_obj': page_obj})

@login_required
def exam_details(request, examination_id):
    faculties = Faculty.objects.all()
    examination = get_object_or_404(Examination, id=examination_id)

    # Get letters related to the examination
    letters = Letter.objects.filter(examination_id=examination_id)

    # Paginate the letters (20 per page)
    paginator = Paginator(letters, 50)
    page_number = request.GET.get("page")

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)  # If page is not an integer, show first page
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)  # If out of range, show last page

    return render(request, "examination/examDetails.html", {
        'examination': examination,
        'page_obj': page_obj,  # Pass only paginated data
        'faculties': faculties
    })

@login_required
def deleteExam(request, examination_id):
    examination = get_object_or_404(Examination, id=examination_id)

    if request.method == 'POST':
        examination.delete()
        messages.success(request, "Examination was deleted successfully")  
        return redirect('examination:index')
    return render(request, 'examination/confirmDelete.html',{'examination':examination})
    #return HttpResponse("All deleted")

@login_required
def examEdit(request, examination_id):
    examination = get_object_or_404(Examination, id=examination_id)

    if request.method == 'POST':
        form = ExamForm(request.POST, instance=examination)
        if form.is_valid():
            form.save()
            messages.success(request, "Examination was updated successfully")  
            return redirect('examination:index')
    else:
        form = ExamForm(instance=examination)
    return render(request, 'examination/examEdit.html',
                      {'form': form, 'examination':examination})


@login_required
def createExam(request):
    #return HttpResponse("I am being served for creating of exams");
    if request.method == 'POST':
        
        form = ExamForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Examination was created successfully")  
            return redirect('examination:index')
    else:
        form = ExamForm()
    return render(request, "examination/createExam.html",
                  {'form': form})

templates/examination/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title  %} WACP Examination Letter Solution{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-around align-items-center">
      <a href="#" class="logo">
        <img src="{% static 'images/Roundlogo.png' %}" >
        WACPCOAM
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->


        {% if user.is_authenticated %}
        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <span class="d-none d-md-block dropdown-toggle ps-2">Welcome {{ user.username }}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
            
              <h6>Welcome {{user.username}}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>
{% endif %}
          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" href="#">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'examination:index' %}">
          <i class="bi bi-grid"></i>
          <span>Examinations</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'letter:index' %}">
          <i class="bi bi-grid"></i>
          <span>Letters</span>
        </a>
      </li>

   

    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}

  


    <div class="pagetitle">
      {% block pagetitle %} Examination {% endblock %}
      
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
      

        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title"></h5>
              
              {% block body %}

              {% endblock %}

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright West African College of Physicians<strong>. All Rights Reserved
        <br><span>Developed by Double-Edge Technologies</span></strong>
    </div>
    <div class="credits">
     </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/chart.js/chart.umd.js"></script>
  <script src="assets/vendor/echarts/echarts.min.js"></script>
  <script src="assets/vendor/quill/quill.js"></script>
  <script src="assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/examination/confirmDelete.html
{% extends 'examination/base.html' %} 

{% block title %} Letter {% endblock %}

{% block pagetitle %} 

{%  endblock %}

{% block body %}

<div class="d-flex justify-content-between align-items-center">
    
    <h2>Are you sure you want to delete "{{ examination.examName }}"?</h2>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
</form>

<a href="{% url 'examination:index' %}" class="btn btn-primary">Cancel</a>


 </div>


{% endblock %}

templates/examination/createExam.html
{% extends 'examination/base.html' %} 
{{ form.media }} # Required for styling/js to make ckeditor5 work   

{% block title %} Create Examination {% endblock %}

{% block pagetitle %}
<div class="d-flex justify-content-between align-items-center">
   <h4>Create Examination</h4> 
<a class="btn btn-primary" href="{% url 'examination:index' %}">Back to Examination List</a>
 
</div>
 {% endblock %}
 <style type="text/css">
 </style>
{%  block body %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

      {% for field in form %}
    <div class="form-group mb-3">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
      {% for error in field.errors %}
        <div class="text-danger">{{ error }}</div>
      {% endfor %}
    </div>
  {% endfor %}
  
    <button type="submit" class="form-control btn btn-primary">Save</button>
</form>
  


{% endblock %}

templates/examination/examDetails.html
{% extends 'examination/base.html' %} 
 {% load static %}
{% block title %} Examination {% endblock %}

{% block pagetitle %}
<div class="d-flex justify-content-between align-items-center">
   <h4>Examination Details:{{ examination.examName }}</h4> 

 
</div>
 
{%  endblock %}

{% block body %}
       <table class="table table-bordered">
        <tr>
          <td>Examination Name</td>
          <td>{{ examination.examName }}</td>
        </tr>
        <tr>
          <td>TOT Topic</td>
          <td>{{ examination.totTopic }}</td>
        </tr>
          <tr>
           <td>TOT Flyer</td>
          <td>
            {% if examination.totFlyers %}
            <img src="{{ examination.totFlyers.url }}" width="500px" alt="totFlyer"/>
            {% endif %}
            </td> 
          </tr>
          <tr>
             <td>TOT Date</td>
          <td>{{ examination.totDate }}</td>
          </tr>
         <tr>
           <td>TOT Details</td>
          <td>{{ examination.totDetails|safe }}</td>
         </tr>
          <tr>
           <td>Arrival Information for CE and others</td>
          <td>{{ examination.arrivalinfo|safe }}</td>
         </tr>
         <tr>
          <td>Ibadan Time Table</td>
          <td>{{ examination.timetableIbadan }} | 
            <a href="{{  examination.timetableIbadan.url }}" target="_blank">View File</a> </td>
         </tr>
          <tr>
             <td>Accra Time Table</td>
          <td>{{ examination.timetableAccra }} |
              <a href="{{  examination.timetableAccra.url }}" target="_blank">View File</a></td>
          </tr>
         <tr>
           <td>Abuja Time Table</td>
          <td>{{ examination.timetableAbuja }} | 
            <a href="{{  examination.timetableAbuja.url }}" target="_blank">View File</a>
          </td>
         </tr>
         <tr>
           <td>Travel Protocol</td>
          <td>{{ examination.travelProtocol }} | 
            <a href="{{  examination.travelProtocol.url }}" target="_blank">View File</a>
          </td>
         </tr>
         
        
       </table>

<h2>Letters:</h2>
<!-- Bordered Table -->
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Surname</th>
      <th scope="col">Name</th>
      <th scope="col">Faculty</th>
      <th scope="col">Examination Center</th>
      <th scope="col">Arrival Date</th>
      <th scope="col">Departure Date</th>
      <th scope="col" width="100px">Email</th>
      <th scope="col" width="100px">User Type</th>
   </tr>
  </thead>
  <tbody>
      {% for letter in page_obj %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ letter.surname }}</td>
      <td>{{ letter.name }}</td>
      <td>{{ letter.faculty }}</td>
      <td>{{ letter.centerOfTheExamination }}</td>
      <td>{{ letter.arrivalDate }}</td>
      <td>{{ letter.depatureDate }}</td>
      <td width="100px">{{ letter.email }}</td>
      <td width="100px">{{ letter.userType }}</td>
      <td>
        <a href="{% url 'letter:details' letter.id  %}"> 
          <button class="btn btn-dark">View </button></a>
         <button class="btn btn-danger">Delete</button>
      </td>
    </tr>
    {%  empty %}
    <h4>This examination has no letters</h4>
    {%  endfor %}
  </tbody>
</table>
<!-- End Bordered Table -->

<!--paginator here-->

<!-- Pagination Controls -->
<div class="pagination">
  {% if page_obj.has_previous %}
      <a href="?page=1">First</a> | 
      <a href="?page={{ page_obj.previous_page_number }}">Previous</a> | 
  {% endif %}

  <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

  {% if page_obj.has_next %}
     |  <a href="?page={{ page_obj.next_page_number }}">Next</a> | 
      <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
  {% endif %}
</div>



{% endblock %}

templates/examination/examEdit.html
{% extends 'examination/base.html' %} 

{% block title %} Create Examination {% endblock %}

{% block pagetitle %}
<div class="d-flex justify-content-between align-items-center">
   <h4>Create Examination</h4> 
<a class="btn btn-primary" href="{% url 'examination:index' %}">Back to Examination List</a>
 
</div>
 {% endblock %}
 <style type="text/css">
 </style>
{%  block body %}

<h3>Edit:  {{ examination.examName }}</h3>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <div class="d-flex justify-content-start space-x:3">
  <button type="submit" class="btn btn-primary btn-lg">Save Changes</button>
    <a href="{% url 'examination:index' %}" class="btn btn-danger btn-lg">Cancel</a>

    </div>
  
</form>
  

{% endblock %}

templates/examination/index.html
{% extends 'examination/base.html' %} 

{% block title %} Examination {% endblock %}

{% block pagetitle %}
<div class="d-flex justify-content-between align-items-center">
   <h4>Examination</h4> 
<a class="btn btn-primary" href="{% url 'examination:createExam' %}">Create Examination</a>
 
</div>
 
{%  endblock %}

{% block body %}
       

<!-- Bordered Table -->
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Examination Name</th>
      <th scope="col">Actions</th>
   </tr>
  </thead>
  <tbody>
      {% for examination in examinations %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ examination.examName }}</td>
      <td>
         <a href="{% url 'examination:details' examination.id %}"> <button class="btn btn-success">View</button></a>
         <a href="{% url 'examination:edit' examination.id %}"><button class="btn btn-primary">Edit </button></a>
       <a href="{% url 'examination:deleteExam' examination.id %}"><button class="btn btn-danger">Delete</button></a> 


      </td>
     
    </tr>
    {%  endfor %}
  </tbody>
</table>
<!-- End Bordered Table -->
<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>



{% endblock %}

templates/examination/loginbase.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title  %} WACP Examination Letter Solution{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
    
              
              {% block body %}
<!--insinde her-->
              {% endblock %}



  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/chart.js/chart.umd.js"></script>
  <script src="assets/vendor/echarts/echarts.min.js"></script>
  <script src="assets/vendor/quill/quill.js"></script>
  <script src="assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>